export const options = [
  {
    label: 'Hitesh Panchal',
    id: 1,
    role: 'Team Lead',
    teamMembers: ['Ekta', 'Nidhi', 'Jaimin'],
    projects: [
      {
        label: 'Google',
        id: 1,
        type: 'Web App',
        tools: ['React', 'Node.js'],
        noOfSprints: 20,
        noOfSprintsCompleted: 5,
        deadline: '2023-12-31',
        milestones: 5,
        milestonesAchieved: 1,
        progress: 25,
      },
      {
        label: 'Meta',
        id: 2,
        type: 'Mobile App',
        tools: ['Flutter', 'Firebase'],
        noOfSprints: 10,
        noOfSprintsCompleted: 8,
        deadline: '2024-06-01',
        milestones: 4,
        milestonesAchieved: 3,
        progress: 80,
      },
    ],
  },
  {
    label: 'Dinesh Suthar',
    id: 2,
    role: 'Team Lead',
    teamMembers: ['Vrutika', 'Amit'],
    projects: [
      {
        label: 'Facebook',
        id: 1,
        type: 'Web App',
        tools: ['React', 'Node.js'],
        noOfSprints: 15,
        noOfSprintsCompleted: 10,
        deadline: '2024-01-15',
        milestones: 3,
        milestonesAchieved: 2,
        progress: 66,
      },
      {
        label: 'Whatsapp',
        id: 2,
        type: 'Mobile App',
        tools: ['Flutter', 'Firebase'],
        noOfSprints: 8,
        noOfSprintsCompleted: 6,
        deadline: '2024-03-01',
        milestones: 4,
        milestonesAchieved: 3,
        progress: 75,
      },
    ],
  },
  {
    label: 'Dimpal Rathod',
    id: 3,
    role: 'Team Lead',
    teamMembers: ['John', 'Doe'],
    projects: [
      {
        label: 'Project C',
        id: 1,
        type: 'Web App',
        tools: ['React', 'Node.js'],
        noOfSprints: 12,
        noOfSprintsCompleted: 9,
        deadline: '2024-02-28',
        milestones: 5,
        milestonesAchieved: 4,
        progress: 80,
      },
      {
        label: 'Project D',
        id: 2,
        type: 'Mobile App',
        tools: ['Flutter', 'Firebase'],
        noOfSprints: 10,
        noOfSprintsCompleted: 7,
        deadline: '2024-04-15',
        milestones: 3,
        milestonesAchieved: 2,
        progress: 66,
      },
    ],
  },
];
